from collections.abc import Sequence

class SearchStrategy[T]: ...

def sampled_from[T](elements: Sequence[T]) -> SearchStrategy[T]: ...
def integers(*, min_value: int | None = ..., max_value: int | None = ...) -> SearchStrategy[int]: ...
