from typing import Generic, Sequence, TypeVar

T = TypeVar("T")

class SearchStrategy(Generic[T]): ...

def sampled_from(elements: Sequence[T]) -> SearchStrategy[T]: ...
def integers(*, min_value: int | None = ..., max_value: int | None = ...) -> SearchStrategy[int]: ...
